apiVersion: v1
kind: Namespace
metadata:
  name: bad-ns

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: restricted-resources
  namespace: bad-ns
spec:
  hard:
    services: 5
    replicationcontrollers: 3
    resourcequotas: 1
    services.loadbalancers  : 23
    secrets: 20
    configmaps: 15
