{{- $name := "restrict-escalation-verbs-roles" }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict Escalation Verbs in Roles
    policies.kyverno.io/category: RBAC Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Role, ClusterRole, RBAC
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      The verbs `impersonate`, `bind`, and `escalate` may all potentially lead to
      privilege escalation and should be tightly controlled. This policy prevents
      use of these verbs in Role or ClusterRole resources.      
spec:
  validationFailureAction: {{ include "vfa-for-pol" (dict "Values" .Values "polname" $name) }}
  background: {{ include "bgscan-for-pol" (dict "Values" .Values "polname" $name) }}
  rules:
    - name: escalate
      match:
        any:
        - resources:
            kinds:
              - Role
              - ClusterRole
      validate:
        message: "Use of verbs `escalate`, `bind`, and `impersonate` are forbidden."
        foreach:
        - list: "request.object.rules[]"
          deny:
            conditions:
              all:
              - key: "{{`{{`}} element.apiGroups || '' {{`}}`}}"
                operator: AnyIn
                value:
                - rbac.authorization.k8s.io
              - key: "{{`{{`}} element.resources || '' {{`}}`}}"
                operator: AnyIn
                value:
                - clusterroles
                - roles
              - key: "{{`{{`}} element.verbs {{`}}`}}"
                operator: AnyIn
                value:
                - bind
                - escalate
                - impersonate
