apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-empty-ingress-host
  annotations:
    policies.nirmata.io/title: Disallow empty Ingress host
    policies.nirmata.io/category: Best Practices
    policies.nirmata.io/severity: medium
    policies.nirmata.io/subject: Ingress
    policies.nirmata.io/description: >-
      An ingress resource needs to define an actual host name
      in order to be valid. This policy ensures that there is a
      hostname for each rule defined.
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: disallow-empty-ingress-host
      match:
        resources:
          kinds:
            - Ingress
      validate:
        message: "The Ingress host name must be defined, not empty."
        deny:
          conditions:
            - key: "{{ request.object.spec.rules[].host || `[]` | length(@) }}"
              operator: NotEquals
              value: "{{ request.object.spec.rules[].http || `[]` | length(@) }}"