apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-secrets
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-secrets
    match:
      any:
      - resources:
          kinds:
          - Secret
    validate:
      message: "Cannot define username and password in secret"
      pattern:
        data:
          username: null
          password: null
